# Generated by Django 2.2.9 on 2025-02-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliacao', 'verbose_name_plural': 'Avaliacoes'},
        ),
    ]
